version: '3.4'

services:
  uds.mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    user: root
    ports:
      - "1187:1433"
    environment:
      MSSQL_SA_PASSWORD: ${MSSQLSAPASSWORD:?api needs database password}
      ACCEPT_EULA: "Y"
  uds.net.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=server=uds.mssql,1433;user id=sa;password=${MSSQLSAPASSWORD:?api needs database password};database=UDSAPI;TrustServerCertificate=True
    ports:
      - "4800:80"
      - "4801:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - uds.mssql