name: Package release to nuget.org

on:
  workflow_dispatch:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  pack:
    name: Package and publish
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Build the projects in solution by building the project that uses them all
      run: dotnet build src/UDS.Net.API -c Release
      
    - name: Pack UDS.Net.API.Client
      run: dotnet pack src/UDS.Net.API.Client -c Release -o .
    
    - name: Pack UDS.Net.API.Entities
      run: dotnet pack src/UDS.Net.API.Entities -c Release -o .
    
    - name: Pack UDS.Net.API.Extensions
      run: dotnet pack src/UDS.Net.API.Extensions -c Release -o .

    - name: Pack UDS.Net.Dto
      run: dotnet pack src/UDS.Net.Dto -c Release -o .

    - name: Push packages to Nuget.org
      run: dotnet nuget push UDS.Net.*.nupkg -k $NUGET_AUTH_TOKEN --source 'https://api.nuget.org/v3/index.json' --skip-duplicate --no-symbols
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_ORG_TOKEN }}
